### ISSUE TITLE
Reporte de práctica - TextBox Personalizado

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Yabin-2021#2]
[Reporte de Práctica - TextBox Personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Yabin-2021/files/6361457/Reporte.de.Practica.-.TextBox.Personalizado.pdf)

[Rúbrica reporte de practica - TextBox personalizado.docx](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Yabin-2021/files/6361573/Rubrica.reporte.de.practica.-.TextBox.personalizado.docx)

**Anexo reporte de práctica en PDF y rúbrica para la evaluación.**

**Comment by salathiel1999** [comment]
Evaluación: 19%
Evaluación: Irvin Barrera

**Comment by josealfredo79** [comment]
Bien hecho y revisado
